# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainform.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("background-image: url(:/background/纯色背景.bmp);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 461, 163))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingbtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.settingbtn.setMinimumSize(QtCore.QSize(131, 131))
        self.settingbtn.setMaximumSize(QtCore.QSize(131, 131))
        self.settingbtn.setStyleSheet("background-image: url(:/set/setting.ico);")
        self.settingbtn.setText("")
        self.settingbtn.setDefault(False)
        self.settingbtn.setFlat(True)
        self.settingbtn.setObjectName("settingbtn")
        self.verticalLayout.addWidget(self.settingbtn)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.musicbtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.musicbtn.setMinimumSize(QtCore.QSize(131, 131))
        self.musicbtn.setMaximumSize(QtCore.QSize(131, 131))
        self.musicbtn.setStyleSheet("background-image: url(:/music/music.ico);")
        self.musicbtn.setText("")
        self.musicbtn.setFlat(True)
        self.musicbtn.setObjectName("musicbtn")
        self.verticalLayout_2.addWidget(self.musicbtn)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(131, 131))
        self.pushButton.setMaximumSize(QtCore.QSize(131, 131))
        self.pushButton.setStyleSheet("background-image: url(:/radio/radio.ico);")
        self.pushButton.setText("")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.gridLayoutWidget.raise_()
        self.settingbtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "         设置"))
        self.label_3.setText(_translate("MainWindow", "         音乐"))
        self.label_4.setText(_translate("MainWindow", "         音乐"))

import setting_rc
